### ISSUE TITLE
Compare model with and without optical flow

### ISSUE THREAD

**Issue by Cardiobotics** [Eiphodos/SUEF#10]
This needs to be fixed first: https://github.com/Cardiobotics/SUEF/issues/12
Baseline settings: https://app.neptune.ai/eiphodos/SUEF/e/SUEF-479/all?path=parameters

**Comment by Gholle-e** [comment]
Baseline settings with MSE loss w/o optical flow: https://app.neptune.ai/jenniferalven/lvef/e/LVEF-102/charts

**Comment by Gholle-e** [comment]
- Baseline settings W/O optical flow:
Run 1: https://app.neptune.ai/jenniferalven/lvef/e/LVEF-136/charts
Run 2: https://app.neptune.ai/jenniferalven/lvef/e/LVEF-137/charts

- Comparison with optical flow (LVEF-131): https://app.neptune.ai/jenniferalven/lvef/experiments?compare=IwZmBoFZ2I&split=cmp&dash=charts&viewId=standard-view
