### ISSUE TITLE
Compare model with different losses

### ISSUE THREAD

**Issue by Cardiobotics** [Eiphodos/SUEF#11]
This needs to be fixed first: https://github.com/Cardiobotics/SUEF/issues/12
Baseline settings: https://app.neptune.ai/eiphodos/SUEF/e/SUEF-479/all?path=parameters

Classification - cross-entropy loss
Regression - mse loss
Ordinal regression - all-threshold loss

**Comment by Gholle-e** [comment]
- Classification - cross-entropy loss: https://app.neptune.ai/jenniferalven/lvef/e/LVEF-134/charts
- Regression - mse loss: https://app.neptune.ai/jenniferalven/lvef/e/LVEF-131/charts
- Ordinal regression - all-threshold loss: https://app.neptune.ai/jenniferalven/lvef/e/LVEF-132/charts

- Comparison: https://app.neptune.ai/jenniferalven/lvef/experiments?compare=IwZmBoIJiA&split=cmp&dash=charts&viewId=standard-view
