### ISSUE TITLE
Re-train 2-stream model with new pre-processing and evaluate on EchoNet

### ISSUE THREAD

**Issue by jenniferalven** [Eiphodos/SUEF#13]
New-pre processing: FPS (frames per second) instead of HRPS (heart rate per second)

Training data: Only 4-chamber views, two differents experiments:
* Training data: ours, test data: EchoNet
* Training data: EchoNet, test data: EchoNet

Note: We vill need to generate flow-data for the EchoNet data

https://echonet.github.io/dynamic/

**Comment by Gholle-e** [comment]
- Training data: ours, test data: EchoNet: https://app.neptune.ai/jenniferalven/lvef/e/LVEF-207/charts (fine-tuned on SUEF-468)
- Training data: ours, test data: EchoNet: https://app.neptune.ai/jenniferalven/lvef/e/LVEF-232/charts (fine-tuned on SUEF-479)

**Comment by Gholle-e** [comment]
All test data generated.
