### ISSUE TITLE
Re-train 4-stream model with new pre-processing and evaluate on CAMUS

### ISSUE THREAD

**Issue by jenniferalven** [Eiphodos/SUEF#14]
New-pre processing: Resample images such that all images have the same amount of slices (alla images represent the exact same phase of the cardiac cycle so we don't need to resample with respect to e.g. fps).

Training data: 90% of CAMUS train , test data: 10% of CAMUS train
Note: We vill need to generate flow-data for the CAMUS data

https://www.creatis.insa-lyon.fr/Challenge/camus/

**Comment by Gholle-e** [comment]
https://app.neptune.ai/jenniferalven/lvef/e/LVEF-257/charts

**Comment by Gholle-e** [comment]
Test data generated.

**Comment by Gholle-e** [comment]
New test data generated in LVEF-262.

**Comment by Gholle-e** [comment]
Retry with the full Camus dataset.

**Comment by Gholle-e** [comment]
Complete Camus dataset (validated on test data):
https://app.neptune.ai/jenniferalven/lvef/runs/details?viewId=standard-view&detailsTab=charts&shortId=LVEF-289&type=run
