### ISSUE TITLE
Run EchoNet-dynamic on our test data

### ISSUE THREAD

**Issue by jenniferalven** [Eiphodos/SUEF#15]
Two experiments:
* Run as it is
* Investigate if it is possible to fine-tune it on our training data

https://github.com/echonet/dynamic

**Comment by Cardiobotics** [comment]
Rember: new pre-processing FPS (frames per second) instead HRPS (heart rate per second)

**Comment by Gholle-e** [comment]
EchoNet fine-tuned on our training data: https://app.neptune.ai/jenniferalven/lvef/e/LVEF-241/charts

**Comment by Gholle-e** [comment]
- Run as it is: r2plus1d_18_suef_testdata.csv
- Investigate if it is possible to fine-tune it on our training data: fine_tuned_lvef_241_r2plus1d_18_ep_40_suef_testdata.csv
