### ISSUE TITLE
Use echonet as backbone instead of ours

### ISSUE THREAD

**Issue by jenniferalven** [Eiphodos/SUEF#16]
Decide for e.g. three differents backbone networks from action/video classification/recognition (https://paperswithcode.com/task/action-recognition-in-videos, https://paperswithcode.com/task/action-classification, https://paperswithcode.com/task/video-classification)
Compare with ours in 2-, 4-, 6- and 8-stream settings respectively

**Comment by Gholle-e** [comment]
Status: Data generated. The issue will be finished when needed.
