### ISSUE TITLE
Re-train 8-stream model with new pre-processing and evaluate on EchoNet and our test data

### ISSUE THREAD

**Issue by Cardiobotics** [Eiphodos/SUEF#17]
* New-pre processing: FPS (frames per second) instead of HRPS (heart rate per second)
* Fine-tune our best 8-stream model: i3d_bert_multi-stream_8-Stream_exp_SUEF-479
* Three differents experiments/tests:
(1) Training data: ours (all views), test data: ours (all views)
(2) Training data: ours (all views), test data: ours (only 4c) 
(2) Training data: EchoNet, test data: EchoNet

**Comment by Gholle-e** [comment]
- Training data: EchoNet, test data: EchoNet: https://app.neptune.ai/jenniferalven/lvef/e/LVEF-224/charts
- Training data: ours (all views): https://app.neptune.ai/jenniferalven/lvef/e/LVEF-231/charts

**Comment by Gholle-e** [comment]
All test data generated.
