### ISSUE TITLE
Ablation study missing views

### ISSUE THREAD

**Issue by Cardiobotics** [Eiphodos/SUEF#18]
Experiment on this paragraph:

 "If a view is missing it is replaced with another view according to the following (descending) priority order: A4C, A2C, A3C, PLAX. This is possible due to the model's shared weights between views, and should increase the model's robustness to missing or misclassified views. Example: Examination includes one A3C, one A4C and one PLAX view which gives the training data input (A4C, A3C, A4C, PLAX). Comparisons to settings where the missing view is replaced with an empty view confirm that this strategy is superior."

I.e. train/evaluate with empty view if view is missing.

**Comment by Gholle-e** [comment]
https://app.neptune.ai/jenniferalven/lvef/e/LVEF-252/charts

**Comment by Gholle-e** [comment]
All test data generated.
