### ISSUE TITLE
Ablation study duplicate views

### ISSUE THREAD

**Issue by Cardiobotics** [Eiphodos/SUEF#19]
Experiments on the following paragraph:

"If an examination includes several instances of the same view, we create data instances of all possible view combinations. This should increase the model's robustness to examinations with varying quality, and works as an augmentation strategy. Further, it eliminates the need for a more sophisticated view classifier that choose between videos of the same view. Example: Examination includes one A2C, one A3C, two AC4 (AC4a and AC4b) and one PLAX which gives the two training data inputs (A2C, A3C, A4Ca, PLAX) and (A2C, A3C, A4Cb, PLAX). Comparisons to settings where only one video for each view is used confirm that this strategy is superior."

I.e. train/evaluate where only one view is chosen is there are many (instead of creating different combinations). Choose the view with the highest view classification probability (if this is not save, choose a random).

**Comment by Gholle-e** [comment]
Random view: https://app.neptune.ai/jenniferalven/lvef/e/LVEF-270/charts

**Comment by Gholle-e** [comment]
Test results generated.
