### ISSUE TITLE
Train and evaluate I3D+BERT with dataset including zoomed views

### ISSUE THREAD

**Issue by Eiphodos** [Eiphodos/SUEF#4]
Current dataset does not include 2c_zoom, 3c_zoom and 4c_zoom. 
New labels and dataset including these has been prepared and a model needs to be trained and evaluated on this new dataset.

**Comment by jenniferalven** [comment]
Does this include "without optical flow" or should we create an additional issue for this?

**Comment by Eiphodos** [comment]
Thats a separate issue, see https://github.com/Cardiobotics/SUEF/issues/6

**Comment by Eiphodos** [comment]
Training and evalution finished.
Result: Slight increase in validation r2 compared to not using zoomed views.
https://app.neptune.ai/eiphodos/SUEF/e/SUEF-468/charts
