### ISSUE TITLE
Compare model with and without BERT

### ISSUE THREAD

**Issue by Cardiobotics** [Eiphodos/SUEF#8]
Baseline settings: https://app.neptune.ai/eiphodos/SUEF/e/SUEF-479/all?path=parameters

This needs to be fixed first: https://github.com/Cardiobotics/SUEF/issues/1, https://github.com/Cardiobotics/SUEF/issues/12

**Comment by Gholle-e** [comment]
Experiment w/o BERT (using pre-trained weights from SUEF-468): https://app.neptune.ai/jenniferalven/lvef/e/LVEF-166/charts
