### ISSUE TITLE
Compare model with different input views

### ISSUE THREAD

**Issue by Cardiobotics** [Eiphodos/SUEF#9]
This needs to be fixed first: https://github.com/Cardiobotics/SUEF/issues/12
Baseline settings: https://app.neptune.ai/eiphodos/SUEF/e/SUEF-479/all?path=parameters

Compare baseline (4 views, 8 streams) with (3 views, 6 streams) and (5 views, 10 streams)

**Comment by jenniferalven** [comment]
Also test:
* 2 streams, one view (4-chamber)
* 4 streams, two views (4-chamber, 2-chamber)

**Comment by jenniferalven** [comment]
Note: validation set should include the same patients, i.e. only patients that has a 4-chamber view.

**Comment by Gholle-e** [comment]
Added support for generating a validation set to include the same patients, i.e. only patients that has a 4-chamber view.

**Comment by Gholle-e** [comment]
(3 views, 6 streams) w/o adjustment for including the same patients in the validation set (as mentioned above): https://app.neptune.ai/jenniferalven/lvef/e/LVEF-140/monitoring

**Comment by Gholle-e** [comment]
Experiments with adjusted validation set.
- 2 streams, 1 view : https://app.neptune.ai/jenniferalven/lvef/e/LVEF-146/charts 
- 4 streams, 2 views: https://app.neptune.ai/jenniferalven/lvef/e/LVEF-147/charts
- 6 streams, 3 views: https://app.neptune.ai/jenniferalven/lvef/e/LVEF-152/charts
- 8 streams, 4 views: https://app.neptune.ai/jenniferalven/lvef/e/LVEF-150/charts
